version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: artec_app
    restart: unless-stopped
    volumes:
      - ../:/var/www/artec
    tty: true
    networks:
      - artec-network

  composer:
    image: composer:latest
    container_name: artec_composer
    volumes:
      - ../:/var/www/arter
    working_dir: /var/www/arter
    networks:
      - artec-network
    depends_on:
      - webserver

  webserver:
    image: nginx:alpine
    container_name: artec_webserver
    restart: unless-stopped
    tty: true
    depends_on:
     - app
    volumes:
      - ../:/var/www/artec
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8880:80"
      - "8843:443"
    networks:
      - artec-network

  db:
    image: mysql:latest
    container_name: artec_db
    restart: unless-stopped
    tty: true
    ports:
      - "8806:3306"
    environment:
      MYSQL_DATABASE: artec
      MYSQL_ROOT_PASSWORD: root
    networks:
      - artec-network

networks:
  artec-network:
    driver: bridge